### ISSUE TITLE
Add configuration option for Micronaut Serialization to fail on floating numbers in integer fields

### ISSUE THREAD

**Issue by runenielsen** [micronaut-projects/micronaut-serialization#547]
### Feature description

Add configuration option for Micronaut Serialization to fail on floating numbers in integer fields.

It should work the same way as this configuration option for Jackson:

```
jackson:
  deserialization:
    accept-float-as-int: false             <--- THIS
```

... so something like:

```
micronaut:
  serde:
    deserialization:
      accept-float-as-int: false
```
